version: '3'
services:
        mc:
                image: mc
                restart: always
                volumes:
                        - "${MCROOT}/world:/minecraft/world"
                        - "${MCROOT}/world_nether:/minecraft/world_nether"
                        - "${MCROOT}/world_the_end:/minecraft/world_the_end"
                        - "${MCROOT}/configs/ops.json:/minecraft/ops.json"
                        - "${MCROOT}/configs/server.properties:/minecraft/server.properties"
                        - "${MCROOT}/configs/whitelist.json:/minecraft/whitelist.json"
                ports:
                        - "25565:25565"
                environment:
                        TZ: "America/NewYork"

   